#pragma once

using namespace ATL;

template <class T>
class CProxy_IMAMSHFlexGridExEvents : public IConnectionPointImpl<T, &__uuidof(_IMAMSHFlexGridExEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
