#pragma once

using namespace ATL;

template <class T>
class CProxy_IMAComboBoxExEvents : public IConnectionPointImpl<T, &__uuidof(_IMAComboBoxExEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
